use assignment;
select * from employee where deptno = 10 and salary>3000;

Select count(*) as firstclass
from students
where marks between 50.0 and 80.0;

Select count(*) as Distinctions
from students
where marks between 80.0 and 100.0;


Select * from students order by marks desc;

SELECT * FROM STATION;
SELECT COUNT(*) FROM STATION;

SELECT DISTINCT CITY FROM STATION
WHERE ID%2 = 0;
SELECT DISTINCT COUNT(CITY) FROM STATION
WHERE ID%2 = 0;

SELECT DISTINCT CITY FROM STATION
WHERE MOD(ID, 2) = 0;
SELECT DISTINCT COUNT(CITY) FROM STATION
WHERE MOD(ID, 2) = 0;
SELECT (SELECT COUNT(*) FROM STATION N) - (SELECT DISTINCT COUNT(CITY) FROM STATION N1
WHERE MOD(ID, 2) = 0) as No_of_Cities FROM STATION AS DIFFERENCE;
-- 5_a
SELECT  DISTINCT(CITY) FROM STATION
WHERE (CITY LIKE 'A%')
OR (CITY LIKE 'E%')
OR (CITY LIKE 'I%')
OR (CITY LIKE 'O%')
OR (CITY LIKE 'U%');
-- 5_b
SELECT DISTINCT(CITY) FROM STATION
WHERE (CITY LIKE 'A%A' OR CITY LIKE 'A%E' OR CITY LIKE 'A%I' OR CITY LIKE 'A%O' OR CITY LIKE 'A%U')
OR (CITY LIKE 'E%A' OR CITY LIKE 'E%E' OR CITY LIKE 'E%I' OR CITY LIKE 'E%O' OR CITY LIKE 'E%U')
OR (CITY LIKE 'I%A' OR CITY LIKE 'I%E' OR CITY LIKE 'I%I' OR CITY LIKE 'I%O' OR CITY LIKE 'I%U')
OR (CITY LIKE 'O%A' OR CITY LIKE 'O%E' OR CITY LIKE 'O%I' OR CITY LIKE 'O%O' OR CITY LIKE 'O%U')
OR (CITY LIKE 'U%A' OR CITY LIKE 'U%E' OR CITY LIKE 'U%I' OR CITY LIKE 'U%O' OR CITY LIKE 'U%U');

-- 5_c
SELECT DISTINCT(CITY) FROM STATION
WHERE (CITY NOT LIKE 'A%')
AND (CITY NOT LIKE 'E%')
AND (CITY NOT LIKE 'I%')
AND (CITY NOT LIKE 'O%')
AND (CITY NOT LIKE 'U%'); 
-- 5_d
SELECT DISTINCT(CITY) FROM STATION
WHERE (CITY NOT LIKE 'A%A' AND CITY NOT LIKE 'A%E' AND CITY NOT LIKE 'A%I' AND CITY NOT LIKE 'A%O' AND CITY NOT LIKE 'A%U')
AND (CITY NOT LIKE 'E%A' AND CITY NOT LIKE 'E%E' AND CITY NOT LIKE 'E%I' AND CITY NOT LIKE 'E%O' AND CITY NOT LIKE 'E%U')
AND (CITY NOT LIKE 'I%A' AND CITY NOT LIKE 'I%E' AND CITY NOT LIKE 'I%I' AND CITY NOT LIKE 'I%O' AND CITY NOT LIKE 'I%U')
AND (CITY NOT LIKE 'O%A' AND CITY NOT LIKE 'O%E' AND CITY NOT LIKE 'O%I' AND CITY NOT LIKE 'O%O' AND CITY NOT LIKE 'I%U')
AND (CITY NOT LIKE 'U%A' AND CITY NOT LIKE 'U%E' AND CITY NOT LIKE 'U%I' AND CITY NOT LIKE 'U%O' AND CITY NOT LIKE 'U%U');

-- 6Q
SELECT EMP_NO, FIRST_NAME, LAST_NAME, GENDER, HIRE_DATE, (((CURDATE()) - (HIRE_DATE))%30) AS EXPERIENCE_MONTHS, SALARY FROM EMP
WHERE SALARY > 2000 
AND 
(((CURDATE()) - (HIRE_DATE))%30) < 36
ORDER BY SALARY DESC;

-- 7Q
SELECT DEPTNO, SUM(SALARY) FROM EMP
GROUP BY DEPTNO;

-- 8Q
SELECT COUNT(DISTRICT) as No_of_Districts FROM CITY
WHERE POPULATION >100000;

SELECT DISTRICT FROM CITY
WHERE POPULATION >100000 

-- 9Q
SELECT SUM(POPULATION) AS TOTAL_POPULATION FROM CITY
WHERE DISTRICT = 'CALIFORNIA'; 
-- 10Q
SELECT COUNTRYCODE, AVG(POPULATION) FROM CITY
GROUP BY COUNTRYCODE; 

-- 11Q
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMERS;
SELECT STATUS, ORDERNUMBER, CUSTOMERNUMBER, CUSTOMERNAME, COMMENTS FROM ORDERS
INNER JOIN
CUSTOMERS
USING (CUSTOMERNUMBER)
WHERE STATUS = 'DISPUTED';
SELECT COUNT(STATUS) FROM ORDERS
WHERE STATUS = 'DISPUTED';